#!/usr/bin/env bash
#
# Builds the QuickJS-ng engine that SnapNet ships for yt-dlp's EJS challenge solver.
#
# Why the binaries are committed rather than downloaded at build time: Android only permits
# executing files that live in the app's `nativeLibraryDir`, which is populated from `jniLibs`, so
# the engine has to be part of the APK. Committing them also makes the exact artifact that ships in
# a release reproducible and auditable.
#
# The binaries are built *statically* against musl. A static binary issues raw syscalls and needs no
# dynamic linker, which is what allows an Android app to run an engine that was not compiled against
# bionic. (Android's own linker would otherwise refuse a non-bionic ELF.)
#
# Usage:  tools/build-quickjs.sh [output-dir]     # default: app/src/main/jniLibs
#
# Requirements: zig (https://ziglang.org) on PATH, plus curl/tar.
set -euo pipefail

QJS_VERSION="0.17.0"
WORK="$(mktemp -d)"
OUT="${1:-app/src/main/jniLibs}"
trap 'rm -rf "$WORK"' EXIT

echo "==> downloading QuickJS-ng ${QJS_VERSION}"
curl -sSL -o "$WORK/src.tar.gz" \
  "https://github.com/quickjs-ng/quickjs/archive/refs/tags/v${QJS_VERSION}.tar.gz"
tar -xzf "$WORK/src.tar.gz" -C "$WORK"
SRC="$WORK/quickjs-${QJS_VERSION}"

# qjs.c needs the REPL and standalone entry points, which are generated by the qjsc compiler from
# JavaScript sources. qjsc therefore has to be built for the host first.
echo "==> bootstrapping host qjsc"
zig cc -O2 -D_GNU_SOURCE -I"$SRC" -o "$WORK/qjsc" \
  "$SRC/qjsc.c" "$SRC/quickjs.c" "$SRC/quickjs-libc.c" \
  "$SRC/libregexp.c" "$SRC/libunicode.c" "$SRC/dtoa.c" -lm
mkdir -p "$SRC/gen"
"$WORK/qjsc" -ss -o "$SRC/gen/repl.c" -m "$SRC/repl.js"
"$WORK/qjsc" -ss -o "$SRC/gen/standalone.c" -m "$SRC/standalone.js"

build() {
  local target="$1" abi="$2"
  echo "==> building ${abi} (${target})"
  mkdir -p "$OUT/$abi"
  # -static-pie is required, not cosmetic: Android rejects any ELF in lib/<abi>/ whose e_type is
  # not ET_DYN, and a plain `-static` build produces an ET_EXEC executable, which makes the whole
  # APK fail to install ("the package appears to be invalid"). A static PIE has e_type = ET_DYN
  # while still needing no dynamic linker, which musl provides on Android.
  zig cc -target "$target" -static-pie -fPIE -pie -O2 -Wl,-s -D_GNU_SOURCE -I"$SRC" \
    -o "$OUT/$abi/libqjs.so" \
    "$SRC/qjs.c" "$SRC/quickjs.c" "$SRC/quickjs-libc.c" \
    "$SRC/libregexp.c" "$SRC/libunicode.c" "$SRC/dtoa.c" \
    "$SRC/gen/repl.c" "$SRC/gen/standalone.c" -lm
}

build aarch64-linux-musl  arm64-v8a
build arm-linux-musleabihf armeabi-v7a
build x86-linux-musl      x86
build x86_64-linux-musl   x86_64

echo "==> done"
ls -la "$OUT"/*/libqjs.so
